### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by mayinghua** [shinytang6/SchoolInfo#1]
这个repo是不是你们组的官方repo？

**Comment by shinytang6** [comment]
是的，之前由于我们没有权限在SE407下上传代码，所以开了这个repo

**Comment by mayinghua** [comment]
现在应该可以了。你们再试试把代码传到SE407你们自己的repo里。有什么问题，还可以在这里留言。我能看到。

**Comment by shinytang6** [comment]
好的，那我把代码迁移到SE407下

**Comment by mayinghua** [comment]
我给了你repo管理的权限。另外，组内其他同学也被邀请进组了。他们也需要各自提交各自的代码。
